### ISSUE TITLE
Private key in `webpubViewer.pem`?

### ISSUE THREAD

**Issue by danielweck** [edrlab/webpub-viewer#1]
https://github.com/edrlab/webpub-viewer/blob/jellybooks-shared/webpubViewer.pem

Is that okay?

**Comment by danielweck** [comment]
Ah, I must pay more attention to the README:
https://github.com/edrlab/webpub-viewer/blob/jellybooks-shared/README.md#static
Closing.

**Comment by JayPanoz** [comment]
Ah yeah can confirm that was intentional i.e. it can be a pain to deal with if you never did that, or did it long ago – so it was either committing it has webpack-dev is doing for instance, or an how-to for 3 different platforms in the doc.

That said, if you have a better option, I’m all ears – [it is the go-to option in Let’s Encrypt docs](https://letsencrypt.org/docs/certificates-for-localhost/) so I’m not necessarily holding my breath but who knows! :-)

**Comment by danielweck** [comment]
Thanks for the LetsEncrypt link! Useful information.

The `selfsigned` NPM package ( https://www.npmjs.com/package/selfsigned ) may offer a more portable / cross-platform solution compared with the OpenSSL CLI, but the most annoying part of the process remains registering the certificate in the operating system.

**Comment by JayPanoz** [comment]
Thanks I’ll take a closer look asap.
